---
version: '3.8'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:5.7
    env_file: mysql/env/docker.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password
    ports:
      - ${DATAHUB_MAPPED_MYSQL_PORT:-3306}:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldata:/var/lib/mysql

  mysql-setup:
    labels:
      datahub_setup_job: true
    build:
      context: ../
      dockerfile: docker/mysql-setup/Dockerfile
    image: ${DATAHUB_MYSQL_SETUP_IMAGE:-acryldata/datahub-mysql-setup}:${DATAHUB_VERSION:-head}
    env_file: mysql-setup/env/docker.env
    hostname: mysql-setup
    container_name: mysql-setup
    depends_on:
      - mysql

  kafka-setup:
    environment:
      - DATAHUB_PRECREATE_TOPICS=${DATAHUB_PRECREATE_TOPICS:-false}

  datahub-gms:
    env_file: datahub-gms/env/docker-without-neo4j.env
    depends_on:
      - mysql
    environment:
      - DATAHUB_SERVER_TYPE=${DATAHUB_SERVER_TYPE:-quickstart}
      - DATAHUB_TELEMETRY_ENABLED=${DATAHUB_TELEMETRY_ENABLED:-true}
    volumes:
      - ${HOME}/.datahub/plugins:/etc/datahub/plugins

  datahub-upgrade:
    build:
      context: ../
      dockerfile: docker/datahub-upgrade/Dockerfile
    image: ${DATAHUB_UPGRADE_IMAGE:-acryldata/datahub-upgrade}:${DATAHUB_VERSION:-head}
    env_file: datahub-upgrade/env/docker-without-neo4j.env
    hostname: datahub-upgrade
    container_name: datahub-upgrade
    command: ["-u", "SystemUpdate"]

volumes:
  mysqldata:
