name: Generate custom GMS image

on:
  workflow_dispatch:

jobs:
  build-gms:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 

      - name: Install JDK8
        run: |
          sudo apt-get -y remove temurin-11-jdk --purge 
          sudo apt-get -y remove temurin-17-jdk --purge
          sudo apt-get -y remove temurin-8-jdk --purge 
          sudo apt-get -y install openjdk-8-jdk 
          java -version
          echo $JAVA_HOME
