name: Generate custom GMS image

on:
  workflow_dispatch:

jobs:
  build-gms:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 

      - name: Install JDK8
        run: |
          sudo apt-get -y remove temurin-11-jdk --purge 
          sudo apt-get -y remove temurin-17-jdk --purge
          java -version
          JAVA_HOME=/usr/lib/jvm/temurin-8-jdk-amd64
          echo $JAVA_HOME
