name: Generate custom GMS image

on:
  workflow_dispatch:

jobs:
  build-gms:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Check Gradle version
        run: |
          gradle --version 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check Docker version
        run: |
          docker --version

      - name: Build gms 
        run: |
          export JAVA_HOME=/usr/lib/jvm/temurin-11-jdk-amd64
          ./gradlew :metadata-service:war:build 
          echo "Copying war file..."
          cp metadata-service/war/build/libs/war.war .

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ssogunletc/datahub-gms
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/datahub-gms/Dockerfile
          push: true
          tags: ssogunletc/datahub-gms:v0.10.2