name: Generate custom GMS image

on:
  workflow_dispatch:

jobs:
  build-gms:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 

      - name: List docker images 
        run: | 
          echo "LS /"
          ls /
          echo "LS" 
          ls 
          echo "PWD"
          pwd