name: Generate custom Datahub Upgrade Image

on:
  workflow_dispatch:

jobs:
  build-gms:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Datahub Upgrade 
        run: |
          ./gradlew :datahub-upgrade:build 
          tree datahub-upgrade

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/datahub-upgrade/Dockerfile
          push: true
          tags: ssogunletc/datahub-upgrade:v0.10.2