name: Generate new Datahub-CLI package. 

on:
  workflow_dispatch:


jobs:
  repackage-datahub-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y twine  
          python3 -m pip install pydantic click pyyaml avro==1.10.2 avro-gen3==0.7.8
          ./metadata-ingestion/scripts/install_deps.sh 

      - name: Build datahub
        run: | 
          ./gradlew 

      - name: Auto Generate code for ingestion code dir
        run: |
          ./metadata-ingestion/scripts/codegen.sh
          ls metadata-ingestion/src/datahub 
    
      - name: (Re)package ingestion code.  
        run: |
          cd metadata-ingestion 
          rm -rf dist/ 
          python setup.py sdist 
          twine upload dist/* -u ssogunle -p  ${{ secrets.PYPI_PASSWD }}