name: Generate new Datahub-CLI package. 

on:
  workflow_dispatch:


jobs:
  repackage-datahub-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: 'pip'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y twine
    
      - name: Package Metadata Ingestion.  
        run: |
          cd metadata-ingestion 
          rm -rf dist/ 
          python setup.py sdist 
          twine upload dist/* -u ssogunle -p  ${{ secrets.PYPI_PASSWD }}