name: spark smoke test
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "metadata_models/**"
      - "metadata-integration/java/datahub-client/**"
      - "metadata-integration/java/spark-lineage"
      - ".github/workflows/spark-smoke-test.yml"
  pull_request:
    branches:
      - master
    paths:
      - "metadata_models/**"
      - "metadata-integration/java/datahub-client/**"
      - "metadata-integration/java/spark-lineage"
      - ".github/workflows/spark-smoke-test.yml"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spark-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Smoke test
        run: |
          ./gradlew :metadata-integration:java:spark-lineage:integrationTest \
             -x :datahub-web-react:yarnTest \
             -x :datahub-web-react:yarnLint \
             -x :datahub-web-react:yarnGenerate \
             -x :datahub-web-react:yarnInstall \
             -x :datahub-web-react:yarnQuickBuild \
             -x :datahub-web-react:copyAssets \
             -x :datahub-web-react:distZip \
             -x :datahub-web-react:jar
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test Results (smoke tests)
          path: |
            **/build/reports/tests/test/**
            **/build/test-results/test/**
            **/junit.*.xml
      - name: Slack failure notification
        if: failure() && github.event_name == 'push'
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: github-activities
